name = "maltagovauctions"
main = "src/workers/index.ts"
compatibility_date = "2025-04-02"

[site]
bucket = "./public"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "maltagovauctions"
database_id = "YOUR_DATABASE_ID_AFTER_CREATION"
